#!/bin/sh

  ping -c3 172.16.66.6
  if [ $? -ne 0 ]
  then 
    nohup /usr/sbin/status_alert 1 1 & 
    exit 0
  fi
  ping -c3 172.16.66.7
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 2 &
    exit 0
  fi
  ping -c3 172.16.66.8
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 3 & 
    exit 0
  fi

  ping -c3 172.16.66.9
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 4 &
    exit 0
  fi

  ping -c3 172.16.66.10
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 5 &
    exit 0
  fi


  ping -c3 172.16.66.67
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 6 &
    exit 0
  fi


  ping -c3 172.16.66.68
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 7 &
    exit 0
  fi

  ping -c3 172.16.66.69
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 8 &
    exit 0
  fi

  ping -c3 172.16.66.70
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 9 &
    exit 0
  fi

  ping -c3 172.16.66.5
  if [ $? -ne 0 ]
  then
    nohup /usr/sbin/status_alert 1 "Statistic" &
    exit 0
  fi
